version: '2'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    restart: always
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - env.list
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    hostname: kafka
    container_name: kafka
    expose:
      - "9093"
      - "9092"
    ports:
      - "9092:9092"
      #- "9093:9093"
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL_SAME_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL_SAME_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: test_in0:1:1,test_in1:1:1,test_out0:1:1,test_out1:1:1 # Edit this to your liking
    env_file:
      - env.list
    depends_on:
      - zookeeper

  mqtt-kafka-bridge:
    build: ../..
    container_name: mqtt-kafka-bridge
    restart: always
    environment:
      MKB_MQTT_BROKER_ADDRESS: mosquitto
      MKB_KAFKA_BROKER_ADDRESS: kafka
      MKB_KAFKA_BROKER_PORT: 9093
      MKB_MQTT_KAFKA_TOPIC_MAPPINGS: "test_in0>>test_in0|test_in1>>test_in1"
      MKB_KAFKA_MQTT_TOPIC_MAPPINGS: "test_out0>>test_out0|test_out1>>test_out1"
    depends_on:
      - kafka
      - mosquitto
